### ISSUE TITLE
FPS drop when close

### ISSUE THREAD

**Issue by gaetanthiesson** [aras-p/UnityGaussianSplatting#10]
After some testing, there seem to be some heavy fps drop (down to 10-40fps from 80+) when the camera is close to a "surface". Reducing if I lower splat scale and getting worst if it's increased. Wondering if it's a know issue with Gaussian splatting or a known bug with this implementation. Thanks!
![Untitled](https://github.com/aras-p/UnityGaussianSplatting/assets/16124367/b0b042f8-8dfb-43be-b3e9-bc29269e6f50)
![Untitled2](https://github.com/aras-p/UnityGaussianSplatting/assets/16124367/fb40eda0-ef44-49e4-89c9-6dca8cc34ac7)

**Comment by aras-p** [comment]
> Wondering if it's a know issue with Gaussian splatting or a known bug with this implementation

When I write in the readme that `it is not fast`, I mean it. There's also `Make rendering faster` under "things to do at some point" in the same readme. So yeah, that.
