### ISSUE TITLE
package.json cannot be found

### ISSUE THREAD

**Issue by omer9214** [aras-p/UnityGaussianSplatting#103]
when i updated to the 0.9.0 version Unity gives me this error
![error](https://github.com/aras-p/UnityGaussianSplatting/assets/91678980/2a04dbf7-d31b-4a32-a914-49328aeb3b6b)

**Comment by aras-p** [comment]
Does the file indicated in the dialog exist? The sample projects layout in this repo is such that the `package` folder should exist two folders above the actual unity project. Is that the case in your clone/checkout/download?

**Comment by omer9214** [comment]
> Does the file indicated in the dialog exist? The sample projects layout in this repo is such that the `package` folder should exist two folders above the actual unity project. Is that the case in your clone/checkout/download?

thanks i didn't realized , now it works perfectly.
