### ISSUE TITLE
Exported ply has no colors

### ISSUE THREAD

**Issue by pkmnjourney** [aras-p/UnityGaussianSplatting#104]
The ply output is missing the color texture 
Below is an image of the exported ply (of garden splat) after loading it into a separate unity scene
![image](https://github.com/aras-p/UnityGaussianSplatting/assets/38611352/8dbe4565-626a-4b1c-8ce8-586688c20740)

**Comment by YIXIN-M** [comment]
My rendering scene cannot be opened and keeps displaying an error message.
![Uploading 2024-03-29 02-18-33屏幕截图.png…]()

**Comment by YIXIN-M** [comment]
My rendering scene cannot be opened and keeps displaying an error message.The following is the content of the error:
1.IndexOutOfRangeException: Invalid kernelIndex (1) passed, must be non-negative less than 19.
GaussianSplatting.Runtime.GaussianSplatRenderer.SortPoints (UnityEngine.Rendering.CommandBuffer cmd, UnityEngine.Camera cam, UnityEngine.Matrix4x4 matrix) (at /home/yixin/桌面/UnityGaussianSplatting/package/Runtime/GaussianSplatRenderer.cs:598)
GaussianSplatting.Runtime.GaussianSplatRenderSystem.SortAndRenderSplats (UnityEngine.Camera cam, UnityEngine.Rendering.CommandBuffer cmb) (at /home/yixin/桌面/UnityGaussianSplatting/package/Runtime/GaussianSplatRenderer.cs:115)
GaussianSplatting.Runtime.GaussianSplatRenderSystem.OnPreCullCamera (UnityEngine.Camera cam) (at /home/yixin/桌面/UnityGaussianSplatting/package/Runtime/GaussianSplatRenderer.cs:193)
UnityEngine.Camera.FireOnPreCull (UnityEngine.Camera cam) (at /home/bokken/build/output/unity/unity/Runtime/Export/Camera/Camera.bindings.cs:543)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&) (at /home/bokken/build/output/unity/unity/Modules/IMGUI/GUIUtility.cs:203)
2.IndexOutOfRangeException: Invalid kernelIndex (0) passed, must be non-negative less than 19.
GaussianSplatting.Runtime.GaussianSplatRenderer.InitSortBuffers (System.Int32 count) (at /home/yixin/桌面/UnityGaussianSplatting/package/Runtime/GaussianSplatRenderer.cs:423)
GaussianSplatting.Runtime.GaussianSplatRenderer.CreateResourcesForAsset () (at /home/yixin/桌面/UnityGaussianSplatting/package/Runtime/GaussianSplatRenderer.cs:408)
GaussianSplatting.Runtime.GaussianSplatRenderer.Update () (at /home/yixin/桌面/UnityGaussianSplatting/package/Runtime/GaussianSplatRenderer.cs:614).
Finally,how can these problems be solved?

**Comment by aras-p** [comment]
PLY export does not export "a mesh", it exports the gaussian splat back into the file. This is meant for saving the 3DGS "edits".
