### ISSUE TITLE
IndexOutOfRangeException: Invalid kernelIndex (0) passed, must be non-negative less than 19.

### ISSUE THREAD

**Issue by YIXIN-M** [aras-p/UnityGaussianSplatting#105]
![mmexport1711618783404](https://github.com/aras-p/UnityGaussianSplatting/assets/162261726/bb971e5b-9b40-48b7-b05a-45e7d536046c)

**Comment by aras-p** [comment]
I see you are using OpenGL. That is definitely not tested. It might work, or it might not. Use Vulkan, or otherwise you're on your own to figure out why the compute shader does not work.
