### ISSUE TITLE
splat render looks weird on vr

### ISSUE THREAD

**Issue by omer9214** [aras-p/UnityGaussianSplatting#107]
I use OpenXr and when i tried to use vr with single pass it didn't work , multi pass did work but when i tried out the scene was looking weird  this only happening in splat rendering mode and not any other modes , also this does not happen with non vr camera so somethings happening with the target eye setting in the camera

**Comment by aras-p** [comment]
I have zero VR devices around, and have not spent any time whatsoever in trying to make it work in VR/XR/AR. It might work, ir might not. There are other reports about this, closing as duplicate: #17, #26
