### ISSUE TITLE
Rendering: non-standard projection matrix with non-full viewport does not render correctly

### ISSUE THREAD

**Issue by vjroba** [aras-p/UnityGaussianSplatting#109]
When the camera's Projection Matrix is set and the Viewport Rect is not 0, 0, 1, 1, the image becomes distorted.
This file is an implementation of a type of FishTank VR or CAVE VR. 
https://drive.google.com/file/d/1nxsJNRDQ0pjozQ3V22nco2ytjLXJn1LW/view?usp=sharing
Please load it into an empty BuiltIn PR project and open the GSTestScene scene. 
The TestCamera scripts on Camera and Camera_half are setting the Projection Matrix to distort the view frustum so that it encompasses the entire Quad. The Viewport Rect for Camera is 0, 0, 1, 1, but for Camera_half, it is 0, 0, 0.5, 1, which results in a significant decrease in image quality for Camera_half.

I need to split the Viewport Rect in half and place two side by side to output side-by-side video for stereoscopic viewing. I would appreciate your help.
![3dgs](https://github.com/aras-p/UnityGaussianSplatting/assets/13079083/ec1e51c6-5083-4e55-ae8e-baeea32aa9a8)

**Comment by aras-p** [comment]
Yeah, quite likely this does not work. Someone would need to figure out how to do all the projection & splatting in screenspace math properly for that case. I very likely won't be doing this, but if someone figures out the required changes and contributes a fix, I'll consider merging it.

**Comment by vjroba** [comment]
Thank you for your response. Given the situation, I will try to reimplement it by rendering to the RenderTexture with a standard projection matrix and then downsizing and redrawing it.

**Comment by chgara** [comment]
hi @vjroba did you solve it?
