### ISSUE TITLE
Performance vs the webgl repo?

### ISSUE THREAD

**Issue by jelmerS2** [aras-p/UnityGaussianSplatting#11]
Hi
Not a critique, just from a technical technical point of view: what is the difference between this repo and this webgl implementation? It seems that the webgl version runs quite smoothly while this Unity repo is maybe less performant? 
https://github.com/antimatter15/splat 

In this repo's readme it mentions 31 fps for the bicycle example on a M chip. The webgl locomotive scene runs 60 fps in safari (which is normally poor) on my M2 which made me think that the webgl version is maybe more performant..

**Comment by aras-p** [comment]
There's like 30 different webgl implementations at this point. Glad you mentioned which one you're interested in!

When I say ` it is not fast` in the readme, and have a `Make rendering faster` in the todo part of the readme, I mean it :)

Wild guess as to what might be different: I don't know. Maybe the locomotive has way fewer splats than the bicycle? Maybe rendering at different resolutions? Maybe they actually optimized rendering already, whereas I have not? etc.

**Comment by JiamingSuen** [comment]
1. The WebGL version by default renders 1/2 resolution on my HiDPI screen (https://github.com/antimatter15/splat/blob/db27473c34b21e9294bd80848380660808b21a4e/main.js#L728).
2. The built-in FPS counter might not be accurate, which can be validated by using https://github.com/mrdoob/stats.js#bookmarklet.
