### ISSUE TITLE
Cannot find GaussianSplat in object hierarchy in Unity on macOS

### ISSUE THREAD

**Issue by nemilya** [aras-p/UnityGaussianSplatting#113]
I attempted to install 3DGS alongside Unity on macOS but encountered an issue at this step:
* `In the GameObject that has a GaussianSplatRenderer script attached.` ...

However, in the top left corner, I only see:

* `Main Camera`
* `Directional Light`

How can I troubleshoot this issue?

Additional information:
* I'm using the `projects/GaussianExample`
* My Unity version is `2022.3.7f1`

Thanks!

**Comment by aras-p** [comment]
Did you open the single unity scene in the sample project (GSTestScene)? That one has the gaussian splat game object in there. If you only have Main Camera and Directional Light, that would mean you did not open any scenes at all, and you get a default "nothing in there" one.

**Comment by nemilya** [comment]
Sorry, inattentively missed the step `and open GSTestScene`, now everything works! My first project in Unit, thanks!
