### ISSUE TITLE
Display anomaly in Iphone14

### ISSUE THREAD

**Issue by JerryWu6288** [aras-p/UnityGaussianSplatting#114]
In my phone ，It looks like this ，Is this project not support Metal？

**Comment by JerryWu6288** [comment]
https://github.com/aras-p/UnityGaussianSplatting/assets/158786004/16519d39-ea32-4404-9123-bfa4d9e82539

**Comment by JerryWu6288** [comment]
Unity in IOS Model ，is not support Vulkan？

**Comment by aras-p** [comment]
As the project readme says:

> This is not tested at all on mobile/web, and probably does not work there

And apparently it does not work indeed. I have not tested on any mobile device, if it does not work, it does not work.

**Comment by JerryWu6288** [comment]
OK，Thank you
