### ISSUE TITLE
How to export Gaussian Splats

### ISSUE THREAD

**Issue by Yuho994** [aras-p/UnityGaussianSplatting#118]
The effect of UnityGaussianSplating is really amazing. Thank you for your tutorial. Further, I would like to export the Gaussian splats model in Unity to .obj or .gltf format, but I am not very familiar with Unity. Is there any way to export it?

**Comment by aras-p** [comment]
Gaussian splats are not a "3d model", they need special non-triangle-mesh rendering to work. So they can't be "exported" as such.
