### ISSUE TITLE
PLY {filePath} read error: currently files larger than 2GB are not supported

### ISSUE THREAD

**Issue by leokinglong** [aras-p/UnityGaussianSplatting#119]
I have a ply file that is larger than 2G that I need to import, and there is an error when importing. 
![image](https://github.com/aras-p/UnityGaussianSplatting/assets/26246461/d862fcee-cbea-4ad4-8192-dea3b609f514)

I looked at the source code because C# NativeArrays has a maximum limit of 2G. 
![image](https://github.com/aras-p/UnityGaussianSplatting/assets/26246461/2191fc43-38f9-4daa-af54-504751b29712)
There is a data overflow:
![image](https://github.com/aras-p/UnityGaussianSplatting/assets/26246461/f489bfe5-4e06-4c48-bd25-bb3c0719d20c)
I tried to modify the source code, but the NativeArrays data structure is used in too many places in the project. 
![image](https://github.com/aras-p/UnityGaussianSplatting/assets/26246461/06cbbbac-d0f6-4c57-902e-941f0af5d6b7)
![image](https://github.com/aras-p/UnityGaussianSplatting/assets/26246461/109118e6-1903-4660-bba8-5ce990daff28)

Do you plan to support file import of more than 2G?

**Comment by aras-p** [comment]
No plans for that right now, since even if it imported correctly, GPU vertex buffer sizes on many platforms/GPUs/APIs are also limited to like 2GB. So it would start failing later on.
