### ISSUE TITLE
Rendering order issue

### ISSUE THREAD

**Issue by YuEBuZu114514** [aras-p/UnityGaussianSplatting#121]
I added some canvases with render mode set to world space, but they always appear in front of the Gaussian model. Is there any way to modify the rendering order? I tried adjusting the CameraEvent in the CommandBuffer and the ZWrite in the shader, but it had no effect.
PS: I'm using URP.
![image](https://github.com/aras-p/UnityGaussianSplatting/assets/55990389/bc173056-820b-40ec-8b4f-95916aad9a59)

**Comment by YuEBuZu114514** [comment]
Well, the problem has been solved. I didn't realize that in URP, CameraEvent needs to be changed to RenderPassEvent, just like Camera.onPreCull needs to be replaced with RenderPipelineManager.beginCameraRendering. These changes were already implemented in the GaussianSplatURPFeature script. Thank you very much for also preparing the functionalities for both URP and HDRP in advance.

**Comment by mattigruener** [comment]
@YuEBuZu114514 Apologies for digging up this old thread. I'm not very familiar with the respective render setup - would you mind letting me know what exactly you did in Unity to get the correct render order? Your second comment seems to suggest that no code changes were needed. Was there anything else you did? Thank you!

**Comment by YuEBuZu114514** [comment]
> @YuEBuZu114514 Apologies for digging up this old thread. I'm not very familiar with the respective render setup - would you mind letting me know what exactly you did in Unity to get the correct render order? Your second comment seems to suggest that no code changes were needed. Was there anything else you did? Thank you!

In the GaussianSplatURPFeature script, around line 60, in the function named create, there is a line renderPassEvent = RenderPassEvent.BeforeRenderingTransparents. You can change BeforeRenderingTransparents to AfterRenderingTransparents. However, this still has some issues. 
Before the change, the canvas in the scene is rendered before the Gaussian model, meaning it will be obscured. After the change, since it is rendered afterward, the model will be obscured regardless of which one is actually in front. However, if your canvas is an image or does not leave any blank space, you can place a quad behind the canvas to replace modifying the render order. This way, the model will be blocked by the quad first, and then the quad will be blocked by the canvas.

**Comment by mattigruener** [comment]
Thank you for your quick response, @YuEBuZu114514 . Appreciate it! I'll have to play around with this some more.
