### ISSUE TITLE
Scene size limit 

### ISSUE THREAD

**Issue by Bin-ze** [aras-p/UnityGaussianSplatting#122]
Dear author：
I noticed that when the size of the ply file exceeds 2gb, the assets will not load. How should I modify this limit

**Comment by aras-p** [comment]
There's no easy way around that. One part is that Unity native byte arrays are limited to 2GB (that one is not very hard to work around, by using arrays of larger type than byte), but another issue is that most GPUs have a limit of 2GB for a GPU buffer.

All in all, right now the limit of a single splat is about 2GB or like 8 million splats. I don't plan on doing any sort of "clever things" to try to improve the situation.
