### ISSUE TITLE
Scene Freezes in Game Mode

### ISSUE THREAD

**Issue by andy-neparidze** [aras-p/UnityGaussianSplatting#123]
I opened a sample project from this repo and started to render from a .ply file, it worked just fine.
When I press play in Unity to enter Game Mode  it gets stuck and I can't navigate in the scene. Is this supposed to happen?
Same issue when I package the project as an application I can open it but it is just one frame and nothings moving.

I would appreciate any input on how to fix this.

**Comment by aras-p** [comment]
I'm not sure I understand what is the issue. What should be moving? Normally when you press Play in Unity, the "game view" becomes active, so if your Scene view and Game view are two tabs of the same window, then this makes the Scene view not be active anymore, and thus you can't use scene view controls.

In the sample project there's absolutely *no* camera control for "the game" implemented.
