### ISSUE TITLE
splats camera render

### ISSUE THREAD

**Issue by jtchira** [aras-p/UnityGaussianSplatting#127]
https://github.com/user-attachments/assets/f36519a4-83a5-444e-9530-19614e4c83e1

First, thanks for this great project. I have a problem when i try to create a scene un VR using quest 2 and open xr, using pc and link cable.
The problem is that the splats rendered follows the movement of the headset, like the rendered splats were tied to the xr origin camera. In the video you can see like the splats move up and down while a cube remains static. I hope you can help me solving this issue.. Thanks

**Comment by aras-p** [comment]
Yes there are various issues with any sort of VR/XR/AR devices, see #17 and other issues. Will close this as duplicate.
