### ISSUE TITLE
Error when project loads and no Tools menu item available (windows 10)

### ISSUE THREAD

**Issue by TimeScience** [aras-p/UnityGaussianSplatting#128]
On windows when I load the sample Unity Gaussian program I get an error on load and if I proceed with the load there is no "Tools" bar item so no way to load a gaussian.

![image](https://github.com/user-attachments/assets/adfc95d8-4ea0-40cb-9baa-35a56919da1d)

I get the same issue with both the _"GaussianExample"_ (Unity 2022.3.7f1) and _"GaussianExample-HDRP"_ (Unity 2022.3.8f1) projects. I have DX12 installed. 

Could easily be something obvious since I'm not a Unity dev, but the error has no information attached to it so I'm not sure how to debug this better. any suggestions appreciated.

![image](https://github.com/user-attachments/assets/17ea5d99-c87b-45f9-b2f2-1c1200580564)

**Comment by aras-p** [comment]
The error message seems to be very... empty? I've no idea why would that happen. Can you look at whether anything is printed in the editor log file? (in this Console window where you see the empty error, press the three-dots icon in top right, there should be an item to open editor log, attach the log here)

**Comment by TimeScience** [comment]
yeah, quite uninformative error message!
Editor.log attached

[Editor.log](https://github.com/user-attachments/files/16520807/Editor.log)

**Comment by aras-p** [comment]
Hmm so Unity fails to compile all the C# code for some strange reason. The editor log is full of failed commands like:
```
##### CommandLine
"D:\Program Files\Unity 2022.3.7f1\Editor\Data\Tools\netcorerun\netcorerun.exe" "D:/Program Files/Unity 2022.3.7f1/Editor/Data/Tools/ScriptUpdater/ApiUpdater.MovedFromExtractor.exe" "Library\Bee\artifacts\mvdfrm\UnityEngine.TLSModule.dll_52B7D2660BF0467B.mvfrm" "D:\Program Files\Unity 2022.3.7f1\Editor\Data\Managed\UnityEngine\UnityEngine.TLSModule.dll"
##### ExitCode
1
```
but I've no idea why or how that would happen. My only guess, maybe this particular Unity version (2022.3.7 and .8) has a bug when it fails to do anything if the project drive (F in your case) is different than the Unity installation drive (D)? Maybe updating to more recent Unity version (2022.3.x whichever is the latest) would improve things?

I'm just guessing randomly. So far it looks like some general Unity issue that for some reason happens on your machine, and not something specific to this guassian splatting project.

**Comment by TimeScience** [comment]
ok, thanks for looking into this. I've made space on my C drive and will re-install everything on the same drive to see if that fixes the issue and then I'll report back.

**Comment by TimeScience** [comment]
You were right it was a weird unity error that was preventing any projects from compiling and providing no informative error messages.

Fixed by clearing the registgry value of "_HKEY_LOCAL_MACHINE\Software\Microsoft\Command Processor\AutoRun_" because who the @#$#@% know why.

(In case this is of use to anyone, solution found here: https://discussions.unity.com/t/the-project-you-are-opening-contains-compilation-errors-when-creating-new-project/901713/5)
