### ISSUE TITLE
About IOS Error

### ISSUE THREAD

**Issue by JerryWu6288** [aras-p/UnityGaussianSplatting#129]
Hello, when I switched to IOS, there was an error message. May I ask what the reason is?
 I need to use this plugin to support IOS functionality. Can you please help me adapt to the IOS platform?I can pay you the remuneration. Also, could you provide your contact information so that we can have a detailed discussion
![01](https://github.com/user-attachments/assets/9c6be920-870a-4b00-820a-b4e28cf08b18)
![02](https://github.com/user-attachments/assets/2a1b7c62-9f4c-497d-b568-93f6da9ab10e)

**Comment by aras-p** [comment]
I don't know what the issue is; iOS in general is known to have issues with some older devices at least (#72). Your issue is not on the device but in the editor though.

> Can you please help me adapt to the IOS platform

I don't. But maybe you can find someone else to figure out the problem.
