### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by Vkucukemre** [aras-p/UnityGaussianSplatting#13]
Hello, 
The tools menu only has Capture Screenshot and Validate Rendering options
There are no error messages. 
![image](https://github.com/aras-p/UnityGaussianSplatting/assets/12595321/1fa7cfdf-aa3d-4609-82a5-e2cc10c635ae)

**Comment by aras-p** [comment]
That's expected. It used to have menu for creating the splat assets, but that is no longer needed after recent changes. Read the readme again.
