### ISSUE TITLE
Don't support apple vision pro?

### ISSUE THREAD

**Issue by yl1994yl** [aras-p/UnityGaussianSplatting#130]
I tried GaussianExample-URP projects in unity, it works in game.But when i built the package to vision pro, i can't see the model.
<img width="978" alt="截屏2024-08-10 13 37 13" src="https://github.com/user-attachments/assets/53bf9708-5e97-4833-8e24-10b14a89bdbe">

**Comment by aras-p** [comment]
Correct, pretty much all VR related devices do not work (see #17), mostly because 1) I have spent exactly zero effort in getting them to work because 2) I don't have any VR devices around.
