### ISSUE TITLE
Have you considered supporting Unreal Engine

### ISSUE THREAD

**Issue by DreamerYinYu** [aras-p/UnityGaussianSplatting#135]
Hello, I think your plugin works very well, even better than other 3DGS plugins in Unreal Engine. May I ask if you are considering supporting Unreal Engine? thank you

**Comment by aras-p** [comment]
I know nothing about Unreal, so definitely "nope", not planning on implementing anything for it. Also, I'm not sure if Unreal is as easily extensible as Unity is.

**Comment by StephenHodgson** [comment]
> Hello, I think your plugin works very well, even better than other 3DGS plugins in Unreal Engine. May I ask if you are considering supporting Unreal Engine? thank you

I don't think you understand the irony of the question you asked 😅

**Comment by DreamerYinYu** [comment]
> > 您好，我认为您的插件效果很好，甚至比虚幻引擎中的其他 3DGS 插件还要好。请问您是否正在考虑支持 Unreal Engine？谢谢
> 
> 我认为你不理解你问😅的问题的讽刺意味

I'm sorry my statement may have been inappropriate, I didn't mean any harm. I tried to reproduce the 3DGS effect in Unreal Engine and Unity Engine, but the 3DGS plugin in Unreal Engine did not look as good as UnityGassianSlatting. Perhaps it was due to my improper use, and I still need to continue learning. Thank you
