### ISSUE TITLE
Unity camera is not able to capture gaussian splatting except view port

### ISSUE THREAD

**Issue by Bluebottle10** [aras-p/UnityGaussianSplatting#138]
Hi,

Thanks for your effort in getting Unity Gaussian Splatting available.
One quick question is that the regular Unity cameras such as Main Camera is not able to render Gaussian Splatting like view port does.
Any idea how to fix this?  I am just trying to figure out how to render Gaussian Splatting in Main Camera.

Please share your thoughts.

Thanks,
Sungshik

**Comment by aras-p** [comment]
Not sure I understand what is the problem.

**Comment by Bluebottle10** [comment]
Thanks for prompt reply.  My question is that from the scene view, I see Gaussian Splatted scene perfectly.  But when I instantiate a camera and see the splatted scene through the camera, the camera does not see the splatted Scene.
It seems the splatted scene is only visible to scene view but not to instantiated camera.

**Comment by aras-p** [comment]
Ah, so you instantiate some camera at runtime, instead of using the camera that is already in the scene?

**Comment by Bluebottle10** [comment]
Well even the "Main Camera" that is already in the scene is not able to see the splatted scene.  However, I see perfectly well from the scene view in Unity.

**Comment by aras-p** [comment]
Ahh, you mean the little preview window. Yeah that one does not show it. I have not investigated why. The actual main camera rendering (i.e. game view) should display it just fine, doesn't it?

**Comment by Bluebottle10** [comment]
Oh I see.  I have not checked it but let me look at it tonight.  Thank you so much!!!

**Comment by Bluebottle10** [comment]
Thank you.  There is no issue anymore

**Comment by Bluebottle10** [comment]
Hi I am sorry the issue is still there.  I can see the splatted scene through the main camera but when I click on play button, the splatted scene disappears.  Is this by the design?

**Comment by Bluebottle10** [comment]
Oh, it was only when I put perception cam.  Please ignore.
