### ISSUE TITLE
Automatically assign an asset

### ISSUE THREAD

**Issue by Vinci881027** [aras-p/UnityGaussianSplatting#139]
Hi, I apologize for asking a basic question. Do you know how to assign an asset through code instead of manually linking it to the Asset field in the Unity Editor? I'm not very familiar with Unity, so I would greatly appreciate any guidance you can provide. Thank you!

**Comment by aras-p** [comment]
@Vinci881027 in the same way as assigning any reference to any other component in Unity, really (getting familiar with Unity would help in general, I guess). Something like:

```
var gsrenderer = gameObjectWithGaussianRenderer.GetComponent<GaussianSplatRenderer>();
gsrenderer.m_Asset = yourAsset;
```

**Comment by Vinci881027** [comment]
Thank you for your response. It is very helpful.
