### ISSUE TITLE
Wavebasic feature unavailable on DX12?

### ISSUE THREAD

**Issue by kennux** [aras-p/UnityGaussianSplatting#144]
Hey,

I'm working on an application using this repository's code as base for rendering gaussian splats and I've come across a really weird issue specific to just one machine (a PC) of a client. Apparently unity initialized the graphics device correctly as DX12 device:

> GfxDevice: creating device client; threaded=1; jobified=1
> d3d12: loaded!
> Direct3D:
>     Version:         Direct3D 12 [level 12.1]
>     Renderer:        NVIDIA GeForce RTX 4080 SUPER (ID=0x2702)
>     Vendor:          NVIDIA
>     VRAM:            16047 MB
>     App VRAM Budget: 13639 MB
>     Driver:          32.0.15.6614

But for some reason the rendering does not work because the 'wavebasic' feature is unavailable? See this section from the error log:

> SplatUtilities.compute: Kernel at index (0) requires features which are unavailable on the current platform - 'wavebasic'. Make sure '#pragma require' is used correctly as unnecessary arguments can restrict platform reach.
> SplatUtilities.compute: Kernel at index (0) is invalid

The same error is generated for every kernel in the SplatUtilities compute shader. I've tested the very same build that fails on the client machine on different devices with different gpus and even different windows versions, but every other device works. Also, Vulkan seems to work on the client's device for some reason with the build but the performance is not optimal so it's not really a solution for my case.

I hope someone here can help me.

**Comment by aras-p** [comment]
About the only two possible causes that come to mind are:
- Their Windows version is really really old. Windows 10 before "Version 1607 (Anniversary Update)" (that's mid-2016) did support DX12, but did not support Shader Model 6.0.
- Their GPU driver is really old. However, theirs seems to be `32.0.15.6614` which is *very new*. Maybe it is buggy in some way?

**Comment by kennux** [comment]
I think you're right here. I've instructed my client to upgrade windows and test again. You can close this for now, thanks for your quick help :)

**Comment by Jt4112** [comment]
Having this issue on windows 11, with newest GeForce graphics driver

**Comment by aras-p** [comment]
> also checked DirectX 12 and on Windows 11

@Jt4112 and the editor is indeed in DX12 mode (usually shown in the unity title bar, e.g. "<DX12>" or "<DX11>")?

**Comment by Jt4112** [comment]
@aras-p  That fixed it! I didn't even realize unity was linked to specific directX modes. Thanks! that was much easier than trying to find and force updates on a company computer lol
