### ISSUE TITLE
How To move Code properly from Package to Assets

### ISSUE THREAD

**Issue by 2333qbyqby** [aras-p/UnityGaussianSplatting#149]
I'm insterested in this project and trying to implement some new work based on this.I first create a new project and then copy the package folder in this repository to Assets,but meets some bug when running
![image](https://github.com/user-attachments/assets/f165aea1-1c8a-455f-bb1f-1d337ce7e78d)
so what's the correct way to move the package?

**Comment by aras-p** [comment]
@2333qbyqby are you sure the error is because you moved the files, and not because the project you're in is using one of graphics APIs not supported by this gaussian splatting code? It *has to be* D3D12, Vulkan or Metal. D3D11 (which I think is still default in Unity on Windows) *does not work*.

**Comment by andybak** [comment]
Another thing to point out is that you don't need to move the files into Assets just to modify them. Local packages are fully editable.

**Comment by 2333qbyqby** [comment]
Think for your reply,I'm not sure the error is because I moved the files,but the demo works well, so maybe it's not because of graphics APIs? I also make it localpackage,but still meet error
![image](https://github.com/user-attachments/assets/a9c29876-2a58-4094-942e-47cefbb1dcca)

**Comment by aras-p** [comment]
@2333qbyqby did you see and check this part?

> the project you're in is using one of graphics APIs not supported by this gaussian splatting code? It has to be D3D12, Vulkan or Metal

**Comment by 2333qbyqby** [comment]
Thanks,I never change the default graphics API before, after I switch the default graphics API in the project setting,it works fine. Sorry for any inconvenience my stupid question may have caused.

**Comment by 2333qbyqby** [comment]
Thanks,I never change the default graphics API before, after I switch the default graphics API in the project setting,it works fine. Sorry for any inconvenience my stupid question may have caused.
