### ISSUE TITLE
Far Gaussians vanishing progressively during zoom in

### ISSUE THREAD

**Issue by KEVIN09876** [aras-p/UnityGaussianSplatting#152]
I'm experiencing an issue with Meta Quest where Gaussian objects from the back to front progressively disappear during zoom operations.

Could you please advise which component needs modification to resolve this? 

Thank you!

**Comment by aras-p** [comment]
Hard to say what is going on without pictures or videos.

That said, I myself have exactly zero VR devices around, and can't advise on anything VR related. If it works, great, if it does not, you're on your own.
