### ISSUE TITLE
Error when creating a new splat using the tool

### ISSUE THREAD

**Issue by cliv3dev** [aras-p/UnityGaussianSplatting#18]
Great work ! 
With latest commit 19794a3 - Simplify validation script,
using paper's splats samples like Room, bicycle or playroom, the creator outputs an error:
![image](https://github.com/aras-p/UnityGaussianSplatting/assets/22072701/a89b662c-3fef-4bcc-ae09-400eb85690bc)
"PLY vertex size mismatch" on the window and nothing is created.
Using U2020.3.7f1, just clone project, open project, import...

**Comment by aras-p** [comment]
@cliv3dev you sure you are pointing to the correct splat file? should point to e.g. `point_cloud/iteration_30000/point_cloud.ply`, *not* the `input.ply` in the root folder (the one in the root folder is **not** the gaussian splat file)

**Comment by cliv3dev** [comment]
You're right @aras-p ! I was not selecting the right file !
Regards
