### ISSUE TITLE
Error on play: "Object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by matthewrbrennan** [aras-p/UnityGaussianSplatting#2]
Getting this error in Unity 2022.3.9:
NullReferenceException: Object reference not set to an instance of an object
GaussianSplatRenderer.OnPreCullCamera (UnityEngine.Camera cam) (at Assets/GaussianSplatting/Scripts/GaussianSplatRenderer.cs:345)
UnityEngine.Camera.FireOnPreCull (UnityEngine.Camera cam) (at <10871f9e312b442cb78b9b97db88fdcb>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)

I'm using a pointcloud.ply from NerfStudio with the transforms.json renamed to the expected "cameras.json"

Not sure where I went wrong, but any guidance would be much appreciated!

**Comment by carlosnavarro-cn** [comment]
I have the same issue. The content of my json file looks very different from your camera.json. Is there a practical way to match the content?

**Comment by aras-p** [comment]
@matthewrbrennan my guess is that there was some other error before that, that causes the later nullref exception. Anything else in the previous console error messages?

@carlosnavarro-cn I only made it support `cameras.json` files as I found them among the Gaussian Splatting paper data files. If you have something that is different format, and you'd like it to be supported by this, then feel free to either send a pull request, or at least show how your file looks like.

**Comment by matthewrbrennan** [comment]
@aras-p So there was! It jumped so quickly to "999+ errors" I didn't think to scroll all the way to the first one, which was this:

Exception: InputVertex size mismatch, we expect 248 file has 27
GaussianSplatRenderer.LoadPLYSplatFile (System.String folder, System.Boolean use30k) (at Assets/GaussianSplatting/Scripts/GaussianSplatRenderer.cs:169)
GaussianSplatRenderer.OnEnable () (at Assets/GaussianSplatting/Scripts/GaussianSplatRenderer.cs:257)

Thanks Aras!

**Comment by aras-p** [comment]
@matthewrbrennan "Exception: InputVertex size mismatch, we expect 248 file has 27" would mean the file is not a PLY file containing Gaussian Splats, but rather a file containing something else (perhaps just a sparse point cloud?)

**Comment by matthewrbrennan** [comment]
@aras-p OK - so that means simply exporting a PLY pointcloud from Nerfstudio won't work - guess I've got to do some more reading up. Thanks!

**Comment by carlosnavarro-cn** [comment]
> @carlosnavarro-cn I only made it support `cameras.json` files as I found them among the Gaussian Splatting paper data files. If you have something that is different format, and you'd like it to be supported by this, then feel free to either send a pull request, or at least show how your file looks like.

Thank you, Aras! I realized I couldn't just use a NeRF transforms.json, but needed to train a Gaussian Splatting scene to get the proper camera.json. I got it working now!
