### ISSUE TITLE
Need suggestion to learn from code

### ISSUE THREAD

**Issue by HrsPythonix** [aras-p/UnityGaussianSplatting#23]
Great work, but want some suggestions about code reading

I have tried your work with unity and run it successfully, I am familiar with NeRF, 3D-Gaussian-Splatting and coding with UE4, but never used Unity before, any suggestions on how to get a quick start on your code?

**Comment by aras-p** [comment]
You mean how to start using this project? (open the project from Unity Hub, open GSTestScene scene in Unity, look around)

Or you mean how to start learning the code? (the C# code is under Assets/GaussianSplatting/Scripts, HLSL code under Assets/GaussianSplatting/Shaders - go and read it)
