### ISSUE TITLE
Change the input data struct, but get wrong model

### ISSUE THREAD

**Issue by Connaught0** [aras-p/UnityGaussianSplatting#27]
Hi! appreciate for your hard work in this project.
     I'm try to set different setting to train my own gaussian model such as lower sh， so when get your project I try to change the data struct of the Input data struct:
 ( point out : I set the sh degree as 1, and cut the normal, because the vertex of my point. my ply just have 104, If add normal it requires 116, so I guess that I need to delete this)( of caurse I changed the error codes in the script)
```
 public struct InputSplatData  
    {  
        public Vector3 pos;  
        //public Vector3 nor;  
        public Vector3 dc0;  
        public Vector3 sh1, sh2, sh3, sh4;  
        public float opacity;  
        public Vector3 scale;  
        public Quaternion rot;  
    } 
```
but I didn't get the right result, what ever the point clouds or renderer result
The point cloud in expect :
![image](https://github.com/aras-p/UnityGaussianSplatting/assets/37895469/7aa971ff-2eeb-47f6-bf82-ce2768d55b54)
The point cloud that i got:
![image](https://github.com/aras-p/UnityGaussianSplatting/assets/37895469/7e73febb-c870-416c-9547-db115bf59486)
The render result:
![image](https://github.com/aras-p/UnityGaussianSplatting/assets/37895469/a4c8a388-529f-43d5-9f68-52b7fe268600)

could you give me some advise? waiting for you reply! : )

**Comment by aras-p** [comment]
Yeah there's a bunch of other assumptions in the code about the data struct layout. It might be easier to pad the data you have with zero SH coefficients, up to the expected size.

**Comment by aras-p** [comment]
Kinda by design, it only supports "full 3rd order SH" data files for now.
