### ISSUE TITLE
Opening "Create GaussianSplat" menu item hangs the unity editor now

### ISSUE THREAD

**Issue by kleinfour** [aras-p/UnityGaussianSplatting#29]
This project was working fantastically for me yesterday, but for some reason Unity is completely unusable now, even when reinstalling Unity 2022.3, Unity Hub, and starting with a fresh copy of this repository.

Upon clicking the "Create GaussianSplat" MenuItem, the _OnGUI_ method is never called in _GaussianSplatAssetCreator.cs_. Then this window shows up and hangs indefinitely (I've let it sit for a couple of hours and nothing changes). Only way to exit the Unity Editor is with a force quit from Windows task manager.
<img width="801" alt="Screenshot 2023-10-12 125126" src="https://github.com/aras-p/UnityGaussianSplatting/assets/66644716/1d904cb5-64b0-4de0-a0be-e0f846aaaae0">

This started after I deleted some Splats in the Editor, exported the new Ply file, and then tried creating a new GaussianSplat. Every time I've clicked on the MenuItem afterwards, the Editor crashes like in the picture no matter what I do.

**Comment by aras-p** [comment]
@kleinfour @kind18 did it start happening when you got some updated version of this project? About the only thing that comes to mind, is maybe something got broken (but not on my machine?) in "[More recent entries in file picker widget](https://github.com/aras-p/UnityGaussianSplatting/commit/01c2371c8d8a62f158a693b2f3c00608736a9972)" commit. Can you try updating to the commit right before it, and see if that works?

**Comment by aras-p** [comment]
Huh weird! I've no idea why that would happen. About the only thing I can suggest is to either try debugging `GaussianSplatAssetCreator.OnGUI` via some C# debugger (visual studio, vscode or rider), or adding a bunch of different Debug.Log statements into that method, and see where exactly it gets stuck. And then let me know.

**Comment by aras-p** [comment]
@kleinfour @kind18 I blindly attempted to add some safeguards against missing/malformed PLY files -- can you check with latest code if that helps?

**Comment by luiscarone** [comment]
> @kleinfour @kind18 I blindly attempted to add some safeguards against missing/malformed PLY files -- can you check with latest code if that helps?

hi There, it's not crashing now. but it prompts a  ply read error. expected X data bytes got Y(>X)...

**Comment by aras-p** [comment]
> hi There, it's not crashing now. but it prompts a ply read error. expected X data bytes got Y(>X).
Call you tell what exactly it says, and maybe also send the ply file somehow?

**Comment by luiscarone** [comment]
for me, at least, it happens when I edit the Ply and export it, to many times. (as a clean up process). The amount of points expected in PLY is different from the files contains.   

https://www.dropbox.com/scl/fi/7fhx8c9v181bq0ho5snvz/Assets.rar?rlkey=bj3xfzwe546dvqakm0y98vuzb&dl=0

this file was exported from: "Export modified PLY" method

**Comment by luiscarone** [comment]
@aras-p what about blender?

**Comment by aras-p** [comment]
How is blender related?

**Comment by aras-p** [comment]
@luiscarone thanks! found the problem, was an unfortunate interaction between your Git configuration set to Windows line endings presumably, and C# multiline string literals using Windows line endings, and my PLY reading code not being very good lol. Should be fixed in latest code now!
