### ISSUE TITLE
Stuck in "waiting for Unity's code in UnityEditor.CoreModule.dll to finish executing" 

### ISSUE THREAD

**Issue by kind18** [aras-p/UnityGaussianSplatting#30]
When the "Create GaussianSplatAsset" is click, I get stuck in this screen and had to close unity with task manager.
![image](https://github.com/aras-p/UnityGaussianSplatting/assets/17354811/fa9e55d0-81f1-45d2-ac89-e84df662754e)
It worked the first time then it wont work again.

I have searched and there are similar situation people ran into, but every solution seems to be different and never explained how they found the solution.

**Comment by aras-p** [comment]
Looks like the same as #29 but right now I don't have any ideas on why.
