### ISSUE TITLE
URP don't work with scene geometry 

### ISSUE THREAD

**Issue by skaale** [aras-p/UnityGaussianSplatting#32]
Cant add unity geometry like primitives , FBX etc..  to the scene when in URP mode it just get really slow! and then the editor crash 
cant debug it

**Comment by skaale** [comment]
it was do to XR enabled in loader

**Comment by smallfly** [comment]
I'm encountering the exact same issue. Could you please share how you solved it?

**Comment by smallfly** [comment]
this is fixed for me - https://github.com/aras-p/UnityGaussianSplatting/issues/68
