### ISSUE TITLE
Method for prerendering splats to improve performance

### ISSUE THREAD

**Issue by dedoubleyou1** [aras-p/UnityGaussianSplatting#33]
A key insight is that rendering a gaussian and then stretching it is essentially the same as stretching and then rendering.

This means you can prerender textures of normalized gaussians with a reasonable selection of possible falloff values and for each splat assign the texture it uses (since falloff per splat doesn't change each frame).

That means each frame is just calculating the directional harmonics per splat, running the bounds calculations for the facing rectangle, and blending the colors with mask textures; which should be extremely fast.

**Comment by aras-p** [comment]
That’s absolutely not the bottleneck. Calculating “the gaussian” part is just one dot product and one exponent, which is _way_ cheaper than sampling the texture.

The slow parts of the rendering right now are: 1) sorting could be made faster, 2) raw amount of alpha blending when tons of splats overlap, and tiny gaussians being suboptimal for the GPU — this can be addressed by writing a compute shader tiled raaterizer, and 3) there’s no culling of gaussians at all, something that could be implemented.

All in all, there are quite obvious ways how to speed this up, “just” they need to get done. But replacing gaussian falloff with a texture lookup is not one of those ways :)
