### ISSUE TITLE
How to unify the default unity rendering pipeline and gaussiansSplats pipeline in your implementation？

### ISSUE THREAD

**Issue by Bin-ze** [aras-p/UnityGaussianSplatting#35]
Thank you for open sourcing such a great project, I tried it to see how it works and was amazed by the results.
I noticed that some 3d assets in unity can be placed to a 3d gaussians scene taking into account their depth as well as occlusion and I'd like to know how this is done？
<img width="984" alt="image" src="https://github.com/aras-p/UnityGaussianSplatting/assets/72087870/9d909b98-7126-4b6c-a86c-0283dc68e2cd">

How did you unify these two pipelines? Does this mean that 3d gaussians can be used as static game maps in unity? Looking forward to your reply

**Comment by aras-p** [comment]
Opaque objects will properly occlude gaussian splats, but that's about it. I documented it some more: https://github.com/aras-p/UnityGaussianSplatting/blob/main/Doc/render-pipeline-integration.md#how-do-gaussians-interact-with-regular-rendering

**Comment by Bin-ze** [comment]
Thank you very much for your reply!
I'm interested in unity, but I don't have any experience with unity at the moment, so your explanation leaves some doubts for me:
1. Regarding the interaction between Gaussian and conventional rendering, do you mean that in the scene, Unity’s built-in opaque objects and Gaussian objects will all be rendered under the current camera perspective? Then use the depth test to determine the occlusion relationship between opaque objects and Gaussian objects?
2. What does it mean that Gaussian are rendered before all transparencies? I'm new to computer graphics and I'm sorry to ask you such a question
3. Is it possible to add dynamic assets to the current 3d Gaussian scene?
4. You mentioned: "GaussianSplatRenderer objects are rendered after all opaque objects and skybox is rendered, and are tested against Z buffer. ", I would like to know where the specific implementation code is.

Looking forward to your reply！
