### ISSUE TITLE
2 differents gaussian splatting in a signle scene rendering problems

### ISSUE THREAD

**Issue by kuyrem1** [aras-p/UnityGaussianSplatting#36]
Hey,
When using 2 gaussian splatting in a scene, one is render on top of the other one. Also when the camera is facing +X the first model in the hierichy is shown on top, and when facing -X it's the other one that is showing on top.
Please let me know if I am doing something wrong.

Maxime

**Comment by aras-p** [comment]
Yes, they are only sorted by their transform position, and will not composite properly if there's significant overlap. I added some documentation about this: https://github.com/aras-p/UnityGaussianSplatting/blob/main/Doc/render-pipeline-integration.md#rendering-order-of-multiple-gaussian-splat-objects
