### ISSUE TITLE
multiple GS in scene composition

### ISSUE THREAD

**Issue by luiscarone** [aras-p/UnityGaussianSplatting#38]
There is z depth fight between multiple GS, dependably on the camera angle, one is totally in the front of the other, but if you move the camera to the side, the other GS moves to the front, with no Blend on the Z axis. Is this an issue of the how GS is made?

At the same time, if you place an object in the scene it Z blends perfectly, and even the GS in scene blends better.

![image](https://github.com/aras-p/UnityGaussianSplatting/assets/22260698/3410c9dc-6144-4d41-8300-ad56d54bfad3)
![image](https://github.com/aras-p/UnityGaussianSplatting/assets/22260698/0466e032-2b96-41b1-8f39-8bcf9bb782e3)
![image](https://github.com/aras-p/UnityGaussianSplatting/assets/22260698/e79af554-3dfb-4ac4-928c-525186fa8f57)

**Comment by aras-p** [comment]
This is not z depth fighting, but rather the issue that there's no "proper sorting" in between multiple GS objects. One GS objects is fully rendered before any other one, and if they overlap you get strange results. See https://github.com/aras-p/UnityGaussianSplatting/blob/main/docs/render-pipeline-integration.md#rendering-order-of-multiple-gaussian-splat-objects
