### ISSUE TITLE
Tools: Merging splats and applying transformations on export

### ISSUE THREAD

**Issue by hybridherbst** [aras-p/UnityGaussianSplatting#39]
From my tests with the current tooling here's two ideas on how to make it even better:

1) a common usecase I see is downloading a .ply, correcting the transformation, cropping to a nice area and then exporting again. Currently, the transformation correction is not "baked" into the exported file – that would be nice.

2) combining and composing splats into a new one – currently this can be done manually by copy-pasting lines in PLY files, but would be nice if there would be a single step of exporting a "root" object and then all SplatRenderers + their transformations + their cutoffs and edits would be applied into a single one.

Point (2) would also be a useful optimization for runtime use: the resulting splat would be sorted properly and the data is smaller than shipping multiple splats. Could theoretically even be a build step if someone wants that! (Work at "High" resolution with any number of splats and at build time select ones are baked back into one splat at "Low" resolution)

**Comment by aras-p** [comment]
Yeah. All of that is Pretty Easy, except properly rotating the spherical harmonics. Which is also doable, but is not like three lines of code.

**Comment by JanaldoChen** [comment]
> Yeah. All of that is Pretty Easy™, except properly rotating the spherical harmonics. Which is also doable, but is not like three lines of code.

Have you accomplished the function of rotation of the spherical harmonics? I also struggle with the rotation of SH, if only rotate the **_xyz_** and **_rotation_** of gaussian splats, it will get worse rendering results.

**Comment by aras-p** [comment]
> Have you accomplished the function of rotation of the spherical harmonics?

Not yet. I'll probably look into using something like https://github.com/andrewwillmott/sh-lib soon (no idea if it's correct or whether it works at all, but unlike most code out there it supports 4th SH order, and does not depend on huge external math libraries)

**Comment by aras-p** [comment]
Done in #51! Seems To Work ™️ for me, including SH rotation.
