### ISSUE TITLE
Gaussian Splats show upside-down in viewport

### ISSUE THREAD

**Issue by carlosnavarro-cn** [aras-p/UnityGaussianSplatting#4]
Although the splats look correct in the game mode, they show upside-down in the viewport. Rotating or scaling by -1 the object doesn't seem to work. Any idea to visualize it in the viewport correctly?

**Comment by aras-p** [comment]
Most (all?) of gaussian splats data sets I've seen have convention that Y axis is "down" which does not match the Unity's "Y axis is up" convention. You can always just change your scene view camera to be upside down.

And yes, I should at some point look at making the Transform of the GS object actually do anything (it is completely ignored currently). Someday.

I'm gonna close this issue -- **this whole project is just my own personal toy box at this moment**. It's not production ready, do not use it, do not request features (yet)!

**Comment by carlosnavarro-cn** [comment]
Good to know. Thank you for your answer!

**Comment by matthewrbrennan** [comment]
@carlosnavarro-cn I fixed it by simply flipping all my input images before running COLMAP

**Comment by carlosnavarro-cn** [comment]
@matthewrbrennan, great advice! Thank you!

**Comment by aras-p** [comment]
FWIW, in the latest version the gaussian splats take object transform into account (for most scenes I found, to get to "normal" orientation you need to rotate by -160 on X axis, and have -1 in Z scale).
