### ISSUE TITLE
Maybe look at making it work in URP/HDRP? Not sure yet

### ISSUE THREAD

**Issue by carlosnavarro-cn** [aras-p/UnityGaussianSplatting#5]
Would the shaders need to be rewritten for URP or HDRP? How could this be achieved?

**Comment by aras-p** [comment]
It's more of the integration into the "rendering pipeline" that would need to be done differently. But in order to do that, I would first need to learn how to actually do it in HDRP & URP. Which I don't have time for right now.

**Comment by aras-p** [comment]
I'm gonna close this issue -- **this whole project is just my own personal toy box at this moment**. It's not production ready, do not use it, do not request features (yet)!

**Comment by carlosnavarro-cn** [comment]
Good to know. Thank you for your answers!
