### ISSUE TITLE
How to get hdrp working?

### ISSUE THREAD

**Issue by luuude** [aras-p/UnityGaussianSplatting#60]
Could you please enlighten me what i am doing wrong? "gaussianSplatRenderSystem" does not exist in the current context.

**Comment by unitycoder** [comment]
- open GaussianSplatHDRPPass.cs file
- Add using GaussianSplatting.Runtime; to the top
- then can follow these steps to add volume and pass https://github.com/aras-p/UnityGaussianSplatting/blob/main/docs/render-pipeline-integration.md

**Comment by luuude** [comment]
Thanks! I got it working.

**Comment by luuude** [comment]
Closing this

**Comment by aras-p** [comment]
Sorry all, I was not testing HDRP/URP and accidentally added compile errors. Fixed now!
