### ISSUE TITLE
measurement

### ISSUE THREAD

**Issue by dux915hhh** [aras-p/UnityGaussianSplatting#61]
Is it possible to measure some width or length in the result from Gaussian? Thank you in advance!

**Comment by unitycoder** [comment]
might be difficult since those splats can be all over the place (different sizes, semitransparent..) ?

my current workaround is to measure against the raw point cloud..
![gaus_measure](https://github.com/aras-p/UnityGaussianSplatting/assets/5438317/862e2b88-e035-4376-9511-719426f73d5e)

**Comment by dux915hhh** [comment]
> might be difficult since those splats can be all over the place (different sizes, semitransparent..) ?
> 
> my current workaround is to measure against the raw point cloud.. ![gaus_measure](https://user-images.githubusercontent.com/5438317/278810392-862e2b88-e035-4376-9511-719426f73d5e.gif) [ ![gaus_measure](https://user-images.githubusercontent.com/5438317/278810392-862e2b88-e035-4376-9511-719426f73d5e.gif) ](https://user-images.githubusercontent.com/5438317/278810392-862e2b88-e035-4376-9511-719426f73d5e.gif) [ ](https://user-images.githubusercontent.com/5438317/278810392-862e2b88-e035-4376-9511-719426f73d5e.gif)

**Comment by dux915hhh** [comment]
That is amazing! Which software did you use to visulize and measure?

**Comment by unitycoder** [comment]
that is from my own point cloud tool,
but you can do the same with any point picking algorithm. (find closest point on ray)

**Comment by dux915hhh** [comment]
> that is from my own point cloud tool, but you can do the same with any point picking algorithm. (find closest point on ray)

 Sorry, I am the beginner of point cloud. Is the tool in your github named UnityPointCloudViewer?

**Comment by unitycoder** [comment]
yes, but i did some modifications to it (which are not yet included on that plugin).
i'd still suggest testing point picking manually first, you can also open the .ply file in CloudCompare to work with it.

**Comment by dux915hhh** [comment]
Fig1 is from nerfstudio, fig2 and fig3 from gaussian. Looking at sidewalk, nerfstudio has much more points than gaussian, why is it? And how can I manipulate directly gaussian result as fig3 in other software and measure it? Thank you in advance. 

![image](https://github.com/aras-p/UnityGaussianSplatting/assets/123088434/1660a021-8958-4448-b91d-6d07613c72d7)
![image](https://github.com/aras-p/UnityGaussianSplatting/assets/123088434/b5cb3ac7-0980-43e2-a03b-d2b3d1937403)
![image](https://github.com/aras-p/UnityGaussianSplatting/assets/123088434/411b4624-a639-45f7-99f8-b448ef6d28d1)

**Comment by unitycoder** [comment]
maybe better open unity forums thread (the add link here), so many questions :)

**Comment by dux915hhh** [comment]
Hahaha, you are my master. I will try.
