### ISSUE TITLE
Platform Question:

### ISSUE THREAD

**Issue by cym63238998** [aras-p/UnityGaussianSplatting#66]
Does this project only support DX12 and Vulkan?

**Comment by aras-p** [comment]
I have tested:
- Windows (DX12 and Vulkan)
- Mac (Metal)

Those work. Everything else may or might not work. DX11 / Windows definitely does not work, I've removed support for it a while ago.

**Comment by cym63238998** [comment]
> I have tested:
> 
> * Windows (DX12 and Vulkan)
> * Mac (Metal)
> 
> Those work. Everything else may or might not work. DX11 / Windows definitely does not work, I've removed support for it a while ago.
My device is  quest3 , It doesn't seem to be too good, I have the idea of running on VR.
Quest is an Android system.

**Comment by cym63238998** [comment]
> > I have tested:
> > 
> > * Windows (DX12 and Vulkan)
> > * Mac (Metal)
> > 
> > Those work. Everything else may or might not work. DX11 / Windows definitely does not work, I've removed support for it a while ago.
> > My device is  quest3 , It doesn't seem to be too good, I have the idea of running on VR.
> > Quest is an Android system.



> I have tested:
> 
> * Windows (DX12 and Vulkan)
> * Mac (Metal)
> 
> Those work. Everything else may or might not work. DX11 / Windows definitely does not work, I've removed support for it a while ago.

Thank you for your answer
