### ISSUE TITLE
Extreme Inspector Material Preview Lag

### ISSUE THREAD

**Issue by Waffle1434** [aras-p/UnityGaussianSplatting#68]
The inspector for MeshRenderers that have materials is *extremely* laggy (0.5s lagspikes) and evident that something evil is happening.
I can see splats in the material's autogenerated preview and they move around when the inspector refreshes.
I can hear their screams as they cry out from the 32x32px prison that can't and probably shouldn't contain them.
The moment the material is removed or the inspector window is closed, the lag goes away.
![image](https://github.com/aras-p/UnityGaussianSplatting/assets/8021358/5ec935d9-6e1d-43b3-b7f1-f0d98c56ddfa)

**Comment by smallfly** [comment]
I have a similar issue. And it makes the Editor crash, if the Inspector is visible.

**Comment by aras-p** [comment]
Are both of you using URP by chance?

**Comment by smallfly** [comment]
Yes I am. Unity 2022.3.9f1.

**Comment by smallfly** [comment]
I pulled the latest version and the issue seems to be fixed. Thanks!

**Comment by Waffle1434** [comment]
Yes I was using URP
