### ISSUE TITLE
Model superposition problem

### ISSUE THREAD

**Issue by lzh960727** [aras-p/UnityGaussianSplatting#73]
When embedding small models in a large model and using the Splats rendering mode, there may be issues with the rendering display, and depth judgment was not made. After trying to add depth judgment, the display effect of the model was poor. When using Debug Points rendering mode, the depth and position information of the model are rendered normally, but there is no rendering effect of Splats. I am a novice in the rendering field. Can you guide me on how to balance depth and rendering effects?

**Comment by aras-p** [comment]
Yes, when multiple gaussian splats overlap each other, they often are not "composited" properly. See "Rendering order of multiple Gaussian Splat objects" here https://github.com/aras-p/UnityGaussianSplatting/blob/main/docs/render-pipeline-integration.md#rendering-order-of-multiple-gaussian-splat-objects
