### ISSUE TITLE
Has issue with rendering in uneven scale of the viewport

### ISSUE THREAD

**Issue by tufeixp** [aras-p/UnityGaussianSplatting#74]
I tried to turn this into desktop 3D, it works but has this issue, the image looks "feathur" like:
![image](https://github.com/aras-p/UnityGaussianSplatting/assets/11953709/fe6d2f86-518e-4378-993a-45e68f036a55)
scale any viewport of the left/right camera to w=1 instead of 0.5 will correct this looking.
I tried with both dual camera or MockHMD, both are the same result.
I guess is has something to do with the half-width pixel render support inside the shader code, please help to look into it.

**Comment by aras-p** [comment]
I'm not sure I understand the issue. Is this something about VR/XR? If so, I have exactly zero VR devices around, and no idea what could be wrong or where.

**Comment by tufeixp** [comment]
It's not related to VR/XR,  only related to the off-axis frustum used to render half sided viewports, it can be viewed on any screen using some parallel viewing method, naked eye or with some lenticular glasses.

**Comment by aras-p** [comment]
Ah, so you're trying to use a non-standard (off-axis) projection matrix somehow? Yeah that probably does not work correctly right now, just like orthoghraphic camera does not (#25), I'm gonna close this as duplicate.

**Comment by tufeixp** [comment]
I have modified the shader code and now it looks correct now.
RenderGaussianSplats.shader:
		float2 _sbsParams = float2(_ScreenParams.x * 2, _ScreenParams.y);
		float2 deltaScreenPos = (quadPos.x * view.axis1 + quadPos.y * view.axis2) * 2 / _sbsParams;
		o.vertex = centerClipPos;
		o.vertex.xy += deltaScreenPos * centerClipPos.w * 2;
