### ISSUE TITLE
Re-Lightning GS

### ISSUE THREAD

**Issue by danielKhora** [aras-p/UnityGaussianSplatting#79]
Any chance for support for Re-Lightning the GS? using normal information

**Comment by aras-p** [comment]
Gaussian Splats do not have normals.

What I've seen some people do, is do "fake lighting" on GS, i.e. use only light range/attenuation (for say point lights) without any directionality information. Some others try to "somehow" render out a screenspace normals buffer out of GS, and do lighting on that.

In any case, I'm not planning to work on any of that in the near future.

**Comment by LoneDev6** [comment]
https://x.com/DSkaale/status/1734527051757924849

**Comment by aras-p** [comment]
> https://x.com/DSkaale/status/1734527051757924849

Sure, cool. There's several hundred new extensions and improvements to 3DGS since mid-2023. But as the project readme says, "Status as of 2023 December is that I'm not planning on any significant further developments". If anyone wants to contribute improvements, they are welcome.

**Comment by LoneDev6** [comment]
> There's several hundred new extensions and improvements to 3DGS since mid-2023

Can't find anything for Unity sadly. Did you find anything in particular?

Thanks for all your efforts though, this project is helping me a lot to understand the whole concept behind 3DGS and spherical harmonics (which most implementations are not even handling).
