### ISSUE TITLE
PLY vertex size mismatch, expected 248 but file had 15

### ISSUE THREAD

**Issue by luis-paolino** [aras-p/UnityGaussianSplatting#81]
Error message when trying to convert a PLY created from metascan app.

**Comment by luis-paolino** [comment]
I was trying to open a normal PLY.

**Comment by yujia-mt** [comment]
same error!
![image](https://github.com/aras-p/UnityGaussianSplatting/assets/138568445/85150405-492e-4abd-ae0c-11652f6246cd)

**Comment by aras-p** [comment]
@yujia-mt this would mean the PLY splat file is of different format than expected. But hard to say how/what, without having the file to look at.
