### ISSUE TITLE
Support Scaffold-GS rendering

### ISSUE THREAD

**Issue by bmikaili** [aras-p/UnityGaussianSplatting#84]
How hard would it be to adjust the code to support the `.ply` files this puts out? https://github.com/city-super/Scaffold-GS

**Comment by aras-p** [comment]
Is there some overview/writeup where one can figure out what their `.ply` files contain?

**Comment by bmikaili** [comment]
Hmm, there's no simple writeup yet and I haven't gotten to digesting the paper yet. I guess once they release their rendering code it's easier to understand

**Comment by inspirelt** [comment]
Hi, thanks for your interests in our work. In scaffold-GS, the scene is structured by a set of voxelized anchors, and each anchor distributes dynamic number of gaussian points for rendering.  The ```.ply``` stores feature vectors and offsets for each gaussian point. Properties, including ```color```, ```opacity```, ```scaling``` and ```rotation```, are decoded from the features using MLPs. We've released a viewer based on the SIBR_viewers. Please feel free to try.

**Comment by luuude** [comment]
Oh that would be awesome! Scaffold-GS is quite an update!

**Comment by aras-p** [comment]
FWIW I'm not planning to add that, but anyone else can of course try doing it.
