### ISSUE TITLE
IndexOutOfRangeException: Invalid kernelIndex (0) passed, must be non-negative less than 20.

### ISSUE THREAD

**Issue by yuancaimaiyi** [aras-p/UnityGaussianSplatting#85]
@aras-p  
Hello ,when I import 3DGS pointcloud to unity ,error:"`IndexOutOfRangeException: Invalid kernelIndex (0) passed, must be non-negative less than 20.
UnityEngine.ComputeShader.GetKernelThreadGroupSizes (System.Int32 kernelIndex, System.UInt32& x, System.UInt32& y, System.UInt32& z) (at <5cd59f99245548bdbfa6531b54530320>:0)` 
So,how do i solve it? thanks

**Comment by aras-p** [comment]
@yuancaimaiyi I'd need more details to be able to tell what's wrong.
- Which Unity version?
- What OS? (Windows, Mac, Linux)
- Which project are you opening?
- What is your GPU?
- What is the full callstack of that error (it is shown in lower part of Unity Console window when you select that error)

**Comment by yuancaimaiyi** [comment]
@aras-p  
Sorry, I forgot to mention my detailed environment.
platform: linux /ubuntu 18.04
unity version : Unityhub has tried various unity versions, 2022, 2023, etc.
project : main branch 
GPU : GTX 1660 Ti 
detil error: `IndexOutOfRangeException: Invalid kernelIndex (0) passed, must be non-negative less than 20.
UnityEngine.ComputeShader.GetKernelThreadGroupSizes (System.Int32 kernelIndex, System.UInt32& x, System.UInt32& y, System.UInt32& z) (at <5cd59f99245548bdbfa6531b54530320>:0)
GaussianSplatting.Runtime.GaussianSplatRenderer.InitSortBuffers (System.Int32 count) (at UnityGaussianSplatting/package/Runtime/GaussianSplatRenderer.cs:423)
GaussianSplatting.Runtime.GaussianSplatRenderer.CreateResourcesForAsset () (at UnityGaussianSplatting/package/Runtime/GaussianSplatRenderer.cs:408)
GaussianSplatting.Runtime.GaussianSplatRenderer.Update () (at UnityGaussianSplatting/package/Runtime/GaussianSplatRenderer.cs:614)`

**Comment by michnaugh1** [comment]
Hi aras-p: Big thanks on your work on this project. I'm experiencing the same problem in this comment. 

Platform: Win11, Ubuntu 22.10
project: 0.8.0
GPU: rtx 4070

I'm trying to use this to develop for an Meta Quest 3. Problem occurs when development set for Quest. No issues when running without Quest settings.

Thanks again. I've really enjoyed following this project.

**Comment by aras-p** [comment]
@michnaugh1 that sounds like the editor is in active platform (Android?) that has OpenGL ES (and not Vulkan) setup as the graphics API, i.e. issue #26 -- currently OpenGL or OpenGL ES is not supported.

**Comment by wushuangge** [comment]
@aras-p @FirepadCN  Hello, I encountered the same issue. However, after I modified it to only use vulkan, the following problem occurred. The system environment is ubuntu22.04, and it seems to still point to the DirectX Shader Compiler.Please help me solve it. Thank you very much.

**Shader error in 'SplatUtilities': Compilation failed:  Couldn't initialize DirectX Shader Compiler library. [0x80070002 - ] at kernel InitDeviceRadixSort**

<img width="1521" height="233" alt="Image" src="https://github.com/user-attachments/assets/38ec9f7a-9583-4a18-8988-980bc3a1fd48" />
