### ISSUE TITLE
Cant get the render to work.  Need guidance.

### ISSUE THREAD

**Issue by Plutoaurus** [aras-p/UnityGaussianSplatting#87]
Hi.
I've opened the GaussianExample as a new project in unity.
Ive gone to tools and created a assett but cannot figure out where to go next.

The instructions keep mentioning GaussianSplatRenderer.  What and where is this.
I cant get the asset into the heirachy.

**Comment by aras-p** [comment]
Create a game object and add GaussianSplatRenderer component to it.
