### ISSUE TITLE
Export ply compressed files

### ISSUE THREAD

**Issue by entracte-arlo** [aras-p/UnityGaussianSplatting#88]
Hi

Is it possible to export the ply compressed files using the different options available with the plug in?
I have imported a dataset using the 5 different quality presets provided (Very High, High, Medium, Low, Very Low)

The data in Unity are different in size and quality, but when I export the compressed ply files, they are all identical to the original, uncompressed file

**Comment by aras-p** [comment]
Same question as #86 and the short answer is "no" since the standard gaussian splat PLY file format is completely uncompressed.
