### ISSUE TITLE
Use plugin in another project

### ISSUE THREAD

**Issue by Le0m1** [aras-p/UnityGaussianSplatting#89]
Hello, I have 2 questions
 1) Is it possible to use it as a plugin already in a finished project (3d urp) 
2) Is it possible to use many ply objects in one project?

**Comment by aras-p** [comment]
> Is it possible to use it as a plugin already in a finished project (3d urp)

Yes. Easiest is probably pointing to the `package` folder of this repository as a package. Or just copying it into your project. The package is also on openupm if that's your thing https://openupm.com/packages/org.nesnausk.gaussian-splatting/

> Is it possible to use many ply objects in one project?

Yes, but if they overlap in 3D space they might not get sorted properly (similar to how when regular semi-transparent 3D objects overlap, there might be sorting issues). See https://github.com/aras-p/UnityGaussianSplatting/blob/main/docs/render-pipeline-integration.md#rendering-order-of-multiple-gaussian-splat-objects
