### ISSUE TITLE
Tools: Changing the pivot point of the splat for exports

### ISSUE THREAD

**Issue by TravisThomp** [aras-p/UnityGaussianSplatting#91]
I'm trying to change the pivot point of splat (for it to be changed on the exported .ply) and wasn't sure if there was a good method (I'm relativity new to Unity, and all of the solutions I've found seem like they wouldn't be relevant to the export ply feature of the plugin). I'm able to change it in the scene with making the Gaussian Splat a child component of a blank scene element, but that's not too useful since I can't export that. 

If there is currently no good solution to this, I can look into adding the feature, I just don't want to reinvent the wheel.

**Comment by TravisThomp** [comment]
Just realized you can just move the splats over the pivot point in the editor which solves my issue :p

**Comment by aras-p** [comment]
Or can just move the whole gaussian splats object, and use this option when exporting:
![image](https://github.com/aras-p/UnityGaussianSplatting/assets/348087/bae51a0b-c9bb-401e-be15-1c1cefd2f6ff)
