### ISSUE TITLE
About low GPU usage in VR mode

### ISSUE THREAD

**Issue by pe-wen** [aras-p/UnityGaussianSplatting#92]
Pipeline: BIRP,URP
Unity editor version: 2022.3.7f1/2022.3.8f1
GPU: RTX 2070
Headset: HTC Vive Pro

Experiencing rendering lag in play mode and gpu usage is 2%(birp)
Seeking to reduce latency

https://github.com/aras-p/UnityGaussianSplatting/assets/150203630/054ca927-52cb-4b65-9655-047074e2ac89

But I've tried Gaussian Splatting VR Viewer
with minimal latency and GPU usage around 30%
I suspect it might be due to shader effects?
As I'm relatively new to Unity, I'm not very familiar with this.

Also, I'd like to ask how to add GaussianSplatURPFeature to the URP renderer settings.
Does URP renderer settings refer to URP global settings?
![GaussianExample-URP - GSTestScene - Windows, Mac, Linux - Unity 2022 3 8f1_ _DX12_ 2024_1_27 下午 09_22_22](https://github.com/aras-p/UnityGaussianSplatting/assets/150203630/a44312b5-048e-487c-a4e7-e06d14082c09)
![GaussianSplatURPFeature cs - Visual Studio Code 2024_1_27 下午 09_21_12](https://github.com/aras-p/UnityGaussianSplatting/assets/150203630/93bbd4f8-da2a-41a7-aac2-37581b58ca7d)

The following image depicts the current situation in URP
![1706430427692](https://github.com/HIHHIYAYAYOO/UnityTest/assets/150203630/d971b0ee-c40a-4a6b-9402-705d545dcde2)

in play mode 
![-1](https://github.com/HIHHIYAYAYOO/UnityTest/assets/150203630/b6731c5d-3d5c-418a-a543-fc7b1b2540b5)

Finally, I'm attempting to fix single-pass mode only rendering a single eye(birp) 
Below is the relevant information I found
[Single-pass instanced rendering and custom shaders](https://docs.unity3d.com/Manual/SinglePassInstancing.html)
but I'm still failing.
I know  author doesn't have VR equipment
If someone with the equipment could tell me where the issue lies, that would be great.

**Comment by aras-p** [comment]
> Experiencing rendering lag in play mode and gpu usage is 2%(birp)

So presumably "something" is busy using CPU, and not the GPU. I dont' know what (in my case -- not VR thought -- it's the GPU that is 100% busy). I would suggest opening Unity Profiler and taking a look at where CPU time ends up being spent. Maybe it's completely outside of the gaussian splatting, and "something else" is busy doing something?

> Also, I'd like to ask how to add GaussianSplatURPFeature to the URP renderer settings.

Maybe this will help, https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@14.0/manual/urp-renderer-feature-how-to-add.html

**Comment by pe-wen** [comment]
profiler (standalone process)
![alltimeline](https://github.com/HIHHIYAYAYOO/UnityTest/assets/150203630/b302fbcb-fcb8-46d6-bdb8-ef0d8d3fab5d)
![playloop](https://github.com/HIHHIYAYAYOO/UnityTest/assets/150203630/f804a0f4-531f-4f1e-9ac5-b189206466c6)

[WaitForRenderThreads](https://forum.unity.com/threads/gfx-waitforrenderthreads-seems-to-some-how-take-up-remaining-frame-time.950734/)
the gpu is 100% 
It seems to be limited by the GPU not being good enough

 In the URP project I found  it already add  a Renderer Feature to a Renderer
and didn't find other Render can be added. Did I miss anything? 

![GaussianExample-URP - GSTestScene - Windows, Mac, Linux - Unity 2022 3 8f1_ _DX12_ 2024_1_31 下午 12_16_38](https://github.com/HIHHIYAYAYOO/UnityTest/assets/150203630/6990d03c-6b50-45c4-9daa-99c7d66a5e2b)
