### ISSUE TITLE
Errors with URP & VR

### ISSUE THREAD

**Issue by stavrosdidakis** [aras-p/UnityGaussianSplatting#93]
I am getting the following errors when I try to run this in URP for VR (Oculus).
Is it possible to fix it or not at all?

`SplatUtilities.compute: Kernel at index (0) requires features which are unavailable on the current platform - 'wavebasic'. Make sure '#pragma require' is used correctly as unnecessary arguments can restrict platform reach.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
GaussianSplatting.Runtime.GaussianSplatRenderer:InitSortBuffers (int) (at ./Packages/Splatting/Runtime/GaussianSplatRenderer.cs:423)
GaussianSplatting.Runtime.GaussianSplatRenderer:CreateResourcesForAsset () (at ./Packages/Splatting/Runtime/GaussianSplatRenderer.cs:408)
GaussianSplatting.Runtime.GaussianSplatRenderer:Update () (at ./Packages/Splatting/Runtime/GaussianSplatRenderer.cs:614)
`

`SplatUtilities.compute: Kernel at index (0) is invalid
UnityEngine.StackTraceUtility:ExtractStackTrace ()
GaussianSplatting.Runtime.GaussianSplatRenderer:InitSortBuffers (int) (at ./Packages/Splatting/Runtime/GaussianSplatRenderer.cs:424)
GaussianSplatting.Runtime.GaussianSplatRenderer:CreateResourcesForAsset () (at ./Packages/Splatting/Runtime/GaussianSplatRenderer.cs:408)
GaussianSplatting.Runtime.GaussianSplatRenderer:Update () (at ./Packages/Splatting/Runtime/GaussianSplatRenderer.cs:614)
`

**Comment by aras-p** [comment]
This is probably kinda same as #26 -- right now this project "most likely" does not work on a mobile GPU (which Quest is) at all, and also likely does not work in VR. Maybe it does, maybe it does not.

The error you get might go away if you make the project use Vulkan instead of OpenGL graphics API. Or it might not. Or the device might not support Vulkan. I don't know, and I have tested on exactly zero mobile or VR setups.

**Comment by Songxinlei** [comment]
Hello, please ask, have you solved this problem?

**Comment by aras-p** [comment]
@Songxinlei if the question is about running it on Quest or some other VR device, then no, that is not solved, and I don't plan on solving it (I have no VR devices to test/develop on). If someone else would contribute a fix that works, I'd gladly accept it, but so far no one did.

**Comment by DebbyX3** [comment]
I had the same problem, even after following #146 - after the VR pull request/support

My issue was strange enough:
- Imported URP project in unity 6000
- Followed the instruction in #146 
- Added Meta XR Interaction SDK (you can probably instead add the whole Meta All-In-One Package, but I didn't need everything)
- Added Meta XR Rig and Interaction Rig
- Added Meta Teleport Building Block
- Added my gaussians -> at this point, no problems, I could see them in the scene
- Saved the project and....

... had a ton of errors about rendering when I reopened the same project (like you)

### **Solution:**
Edit -> Project Settings -> Player -> in Windows/mac/linux tab, scroll to 'other settings' -> Change Graphics API for Windows (in my case) from Direct3D 11 to Direct3D12 -> restart unity

As they say [here](https://discussions.unity.com/t/gaussian-splat-in-vr-in-unity-enquiry/1581298/2):
"The sorting algo in the gaussian splat package is not supported on Win DX11 which is the default Graphics API for most Unity projects. You can change the [graphics API](https://docs.unity3d.com/Manual/GraphicsAPIs.html) to DX12 or Vulkan in the player settings."
