### ISSUE TITLE
compressed .ply as output?

### ISSUE THREAD

**Issue by qiangjiadong** [aras-p/UnityGaussianSplatting#97]
Hi Aras, as a fan of GSPLAT, I wanted to express my appreciation for the various works you have done on it. As an artist who works with game engines and WebXR, I was hoping to inquire about the possibility of a compressed .ply file output on this Unity project. I was wondering if it would be possible to have an option to output a compressed .ply file, which could then be used on other platforms also outside of Unity. 

I hope it might help the spread and more creative recreation and artistic collage of multiple GSPLAT scenes for various platforms based on .ply.

Thank you so much, very keen to know your thoughts on it! thks!

**Comment by qiangjiadong** [comment]
so sorry if i am wrong, I just found EXPORT PLY from the Renderer Script, will try it :)))

**Comment by aras-p** [comment]
What is "compressed PLY output"? (is this the same question as #88 or #86)
