### ISSUE TITLE
The objects are not being rendered correctly

### ISSUE THREAD

**Issue by JerryWu6288** [aras-p/UnityGaussianSplatting#99]
Hello, author：

When there are two or more model objects in the scene, moving the camera should cause the model that is supposed to be below to occlude the model above it. How can this issue be resolved? Here is the video.

https://github.com/aras-p/UnityGaussianSplatting/assets/158786004/5833fe1c-a351-4b1d-9906-ec8e608da6ae

**Comment by JerryWu6288** [comment]
Who can tell me how to solve this problem? Thank you very much

**Comment by aras-p** [comment]
Short answer is, you can't (without merging the objects into one splat). Longer answer here https://github.com/aras-p/UnityGaussianSplatting/blob/main/docs/render-pipeline-integration.md#rendering-order-of-multiple-gaussian-splat-objects

**Comment by BobH233** [comment]
Hi @aras-p , so if I want to implement the depth check of two 3dgs model (for example I want to put one car model on one outdoor model), how can I do it?

**Comment by aras-p** [comment]
@BobH233 right now they are ordered by their transform position, see sorting inside `GatherSplatsForCamera` function. You'd have to "somehow" sort them differently, maybe by adding some extra parameter to each object and taking that into account while sorting.
